language: php

php:
  - 5.3
  - 5.4
  - 5.5
before_script:
    - printf "\n" | pecl install imagick
    - echo "extension=imagick.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install --no-interaction
notifications:
  email:
    - mrriddick7@gmail.com