language: php

php:
  - 5.3
  - 5.4
  - 5.5
before_script:
    - sudo apt-get install -y imagemagick libtiff-dev libjpeg-dev libdjvulibre-dev libwmf-dev libmagickcore-dev libmagickwand-dev
    - wget http://pecl.php.net/get/imagick-3.1.0RC2.tgz
    - tar -xzf imagick-3.1.0RC2.tgz
    - sh -c "cd imagick-3.1.0RC2 && phpize && ./configure --with-imagick=/usr/local && make && sudo make install"
    - echo "extension=imagick.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install --no-interaction
notifications:
  email:
    - mrriddick7@gmail.com